# Generated by Django 2.2.2 on 2019-06-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_book_category'),
    ]

    operations = [
    ]
