# Generated by Django 2.2.2 on 2019-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
